Models/CharacterViewModel.cs
namespace Exercise4.Models
{
    public class CharacterViewModel
    {
        public string name { get; set; }
        public string city { get; set; }
    }

  

}

Models/CocktailViewModel.cs
namespace Exercise4.Models
{
    // Root myDeserializedClass = JsonConvert.DeserializeObject<Root>(myJsonResponse);
    public class CocktailViewModel
    {

        public string strDrink { get; set; }
        public string strDrinkThumb { get; set; }
        public string idDrink { get; set; }
    }

    public class Root
    {
        public List<CocktailViewModel> drinks { get; set; }
    }


}

Models/ErrorViewModel.cs
namespace Exercise4.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/CharacterController.cs
using Exercise4.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;

namespace Exercise4.Controllers
{
    public class CharacterController : Controller
    {
        public async Task<IActionResult> Index()
        {
            List<CharacterViewModel> characters = new List<CharacterViewModel>();
            string url = "https://mocki.io/v1/d4867d8b-b5d5-4a48-a4ab-79131b5809b8";
            HttpClient httpClient = new HttpClient();
            httpClient.DefaultRequestHeaders.Clear();
            httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            HttpResponseMessage getData = await httpClient.GetAsync(url);

            if (getData.IsSuccessStatusCode)
            {
                string results = await getData.Content.ReadAsStringAsync();
                characters = JsonConvert.DeserializeObject<List<CharacterViewModel>>(results);
            }
            else
            {
                Console.WriteLine("Error calling the web API");
            }

            return View(characters);
        }
    }
}

Controllers/CocktailController.cs
using Exercise4.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;

namespace Exercise4.Controllers
{
    public class CocktailController : Controller
    {

        public async Task<IActionResult> Index()
        {
            List<CocktailViewModel> drinks = new List<CocktailViewModel>();
            string url = "https://www.thecocktaildb.com/api/json/v1/1/filter.php?c=Cocktail";
            HttpClient httpClient = new HttpClient();
            httpClient.DefaultRequestHeaders.Clear();
            httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            HttpResponseMessage getData = await httpClient.GetAsync(url);

            if (getData.IsSuccessStatusCode)
            {
                string results = getData.Content.ReadAsStringAsync().Result;
                JObject json = JObject.Parse(results);
                JArray drinkArray = (JArray)json["drinks"];
                drinks = drinkArray.ToObject<List<CocktailViewModel>>();

            }
            else
            {
                Console.WriteLine("error calling the web API");
            }

          //  HttpClient httpClient = new HttpClient();
          //   HttpResponseMessage getData = await httpClient.GetAsync(url);
            return View(drinks);
        }

    }
}

Controllers/HomeController.cs
using Exercise4.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Exercise4.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Character/Index.cshtml
@model List<Exercise4.Models.CharacterViewModel>

<h1>Characters</h1>
<p>This is the index page of the character Controller</p>

<h1>Character</h1>
<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>City</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var character in Model)
        {
            <tr>
                <td>@character.name</td>
                <td>@character.city</td>
            </tr>
        }
    </tbody>
</table>

Views/Cocktail/Index.cshtml
@model List<Exercise4.Models.CocktailViewModel>

<h1>Cocktails</h1>
<p>This is the index page of the cocktail controller</p>

<table class="table table-striped">
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Picture</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var cocktail in Model)
        {
            <tr>
                <td>@cocktail.idDrink</td>
                <td>@cocktail.strDrink</td>
                <td><img src="@cocktail.strDrinkThumb" width="100" height="100" /></td>
            </tr>
        }
    </tbody>
</table>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Exercise4</title>
    <link rel="stylesheet" href="~/css/BootswatchTheme.css" />
    @*@<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Exercise4.styles.css" asp-append-version="true" /> *@
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Exercise4</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor02">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                                <span class="visually-hidden">(current)</span>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp asp-controller="Character" asp-action="Index">Characters</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp asp-controller="Cocktail" asp-action="Index">Cocktails</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="#">Action</a>
                                <a class="dropdown-item" href="#">Another action</a>
                                <a class="dropdown-item" href="#">Something else here</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Separated link</a>
                            </div>
                        </li>
                    </ul>
                    <form class="d-flex">
                        <input class="form-control me-sm-2" type="search" placeholder="Search">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
        @*<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Exercise4</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp asp-controller="Character" asp-action="Index">Characters</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp asp-controller="Cocktail" asp-action="Index">Cocktails</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav> *@
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Exercise4 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>